### PR TITLE
Mima check for Scala 2.13 #911

### PR DESCRIPTION
**Pull request by explicite**
To enable Mima check for Scala 2.13

Signed-off-by: Jan Paw jpaw@virtuslab.com

### CODE REVIEW

**Review by zsxwing — APPROVED** [review]
LGTM. Thanks!

**Comment by zsxwing** [comment]
@explicite by the way, which author email address you prefer to use when we merging the commit? `tesco.com` or `virtuslab.com`?

**Comment by explicite** [comment]
@zsxwing  please go with `virtuslab.com`

**Comment by zsxwing** [comment]
Cool. Thanks!

**Pull request closed without merging**
