### PR TITLE
[788-DELTA] Update DeltaMergeBuilder documentation: Updated Python Do…

### PR DESCRIPTION
**Pull request by mmengarelli**
…cstring and Javadoc to indidcate that you can any number of whenMatched and whenNotMatched clauses.

Signed-off-by: Mike Mengarelli <mengam01@gmail.com>

### CODE REVIEW

**Comment by scottsand-db** [comment]
Hi @mmengarelli - can you please fix the pycodestyle errors?
https://github.com/delta-io/delta/runs/6329812764?check_suite_focus=true
```
pycodestyle checks failed:
/home/runner/work/delta/delta/python/delta/tables.py:650:93: W291 trailing whitespace
```

**Comment by mmengarelli** [comment]
> Hi @mmengarelli - can you please fix the pycodestyle errors? https://github.com/delta-io/delta/runs/6329812764?check_suite_focus=true
> 
> ```
> pycodestyle checks failed:
> /home/runner/work/delta/delta/python/delta/tables.py:650:93: W291 trailing whitespace
> ```
hi @scottsand-db fixed and pushed. Thanks!

**Comment by mmengarelli** [comment]
Added [1162] - Support database name and table name arguments to DeltaTable.isDeltaTable(). Updated DeltaTable / DeltaTableSuite

**Comment by allisonport-db** [comment]
@mmengarelli as mentioned on #1162, could you create a new PR with those changes and revert this to include just the original changes for #788. Thanks.

**Comment by mmengarelli** [comment]
@allisonport-db reverted to just the changes to resolve [#788 ](https://github.com/delta-io/delta/issues/788)

**Pull request closed without merging**
