### PR TITLE
Fix https://github.com/delta-io/delta/issues/1978

### LINKED ISSUE #1978: Power BI Connector using fn_ReadDeltaTable present duplicated data record[BUG]
## Bug

This is a bug for Power BI connector using fn_ReadDeltaTable. I have been using this connector for almost 2 years, however, lately the dataflow using this connector was showing data duplication issue meanwhile the delta table in azure data lake is completely normal. The issue seems to exist for delta tables that have existed for a long time with delta logs. If I delete the delta table folder and recreate the table from scratch, the issue goes away, but I don't know how long it would last normally. Now I have to resort to the native databricks connector to refresh the delta table.

Due to the nature of the issue, it's hard to recreate the issue as a new delta table won't have the duplication issue. I was wondering if anyone else has similar issue related to the power BI connector to access delta tables in the azure data lake gen 2.

Thanks.

### PR DESCRIPTION
**Pull request by dominikpeter**
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [x] Other (Power BI)

## Description

Fix #1978 

## How was this patch tested?

With local Power BI and sample Dataset

## Does this PR introduce _any_ user-facing changes?

No

### CODE REVIEW

**Comment by dominikpeter** [comment]
I tried to change the PowerBI_Delta.pbit file too. However, I don't think I am able to do it as I don't have the credentials for the Azure Storage Account used in the template. 

Can we still merge the function? It has been tested and solved the issue.

**Comment by gbrueckl** [comment]
Hi @dominikpeter,
while the file `fn_ReadDeltaTable.pq` is the final output for Power BI, I usually also maintain the `.pbit` file for debugging and development of new features. It should be OK to just save the PQ queries in the template and save it without applying the changes.

regarding your change, the fix seems reasonable as the `Extension` column seems to contain everything after the first `.` found in the filename which was not an issue until the `compacted` files were introduced
However, instead of `Text.Mid()` I would rather use `Text.EndsWith()` ([docs](https://learn.microsoft.com/en-us/powerquery-m/text-endswith)) which should be safer to use

If its OK for you, I would take over the ticket, do the changes in the PBIT and fn_ReadDeltaTable 

regards and thanks for your contribution so far!
-gerhard

**Comment by dominikpeter** [comment]
@gbrueckl sure, you can take it over. Thanks a lot.

**Comment by dominikpeter** [comment]
@gbrueckl I am not sure how you want to use `Text.EndsWith()` as the compacted file also end with `.json`.

**Comment by gbrueckl** [comment]
I created a new PR that fixes this issue
https://github.com/delta-io/delta/pull/2101

I also added some documentation for further contributions under /connectors/PowerBI/README.md
Further I changed the sample data to use the Golden Tables provided as part of this repo wherever possible

**Pull request closed without merging**
