### PR TITLE
Support Ceph Storage.

### PR DESCRIPTION
**Pull request by zhangt-nhlab**
We supported the storage of Ceph. Data connection between Delta Lake and Object store system Ceph RGW is established by Openstack Swift API. Path’s scheme is "ceph". Full path is "ceph://{your-cephrgw-container}/{path-to-delta-table}". Please refer to testing file for more detailed configurations. Logstore can use class S3SingleDriverLogStore.

### CODE REVIEW

**Comment by zhangt-nhlab** [comment]
We supported the storage of Ceph. Data connection between Delta Lake and Object store system Ceph RGW is established by Openstack Swift API. Path’s scheme is "ceph". Full path is "ceph://<your-cephrgw-container>/<path-to-delta-table>". Please refer to testing file for more detailed configurations. Logstore can use class S3SingleDriverLogStore.

**Comment by zsxwing** [comment]
Thanks a lot for the contribution. Sorry that I didn't realize you meant a new FileSystem implementation for Ceph. Thought it was a new LogStore implementation. We don't want to maintain FileSystem implementations in the Delta Lake project. You can create your project and publish that to maven central.

**Comment by zhangt-nhlab** [comment]
Thank you for your reply. I wonder if we understand your suggestion correctly. Do you need a log storage implementation such as S3SingleDriverLogStore? If so, we plan to publish the file system to Maven central later, and then adapt the correct CephRGWLogStore to Delta Lake.

**Comment by zsxwing** [comment]
> Do you need a log storage implementation such as S3SingleDriverLogStore?

Yep. 

> If so, we plan to publish the file system to Maven central later,

This would be great.

> and then adapt the correct CephRGWLogStore to Delta Lake.

Do we need a new log store or the user can just S3SingleDriverLogStore (you mentioned this in the PR description)?

**Comment by zhangt-nhlab** [comment]
You are right. As I mentioned before, S3SingleDriverLogStore is a good solution. After we successfully open to Maven central, we will conduct some more detailed tests to verify the adaptation of S3SingleDriverLogStore on this function. If there is no problem, it is best to use S3SingleDriverLogStore only, and we are inclined to do so. Thank you for your reply.

**Comment by zsxwing** [comment]
Cool! Thanks for raising the PR! I'm going to close this as it's not needed.

**Pull request closed without merging**
