### PR TITLE
Add docs for optimized write

### PR DESCRIPTION
**Pull request by weiluo-db**
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [x] Other (Docs)

## Description

Optimized write feature was added by https://github.com/delta-io/delta/pull/2145. This PR adds the corresponding documentation for the feature.

## How was this patch tested?

Docs-only changes.

## Does this PR introduce _any_ user-facing changes?

No

### CODE REVIEW

**Comment by weiluo-db** [comment]
Here is how the docs are rendered:

image
image

**Comment by weiluo-db** [comment]
@rahulsmahadev Could you please take a look since you reviewed the original PR? Thanks!

**Review by rahulsmahadev — APPROVED** [review]
LGTM!

**Review by vkorukanti — APPROVED** [review]
thanks for the docs!

**Pull request merged**
