### PR TITLE
Use Set.empty instead of Set() in DelayedCommitProtocol

### PR DESCRIPTION
**Pull request by takezoe**

### CODE REVIEW

**Comment by mukulmurthy** [comment]
Hi @takezoe,

Thanks for your contribution! Can you please explain the benefits of this change?

**Comment by takezoe** [comment]
For unification of code style because `Collection.empty` is used to create an empty collection in other parts of Delta Lake codebase. Also `Seq()` calls `Seq.empty` internally, but direct call is a bit more efficient.

**Comment by mukulmurthy** [comment]
Makes sense. Can you update your PR title to say Set instead of Seq please? Will approve it after that.

**Comment by takezoe** [comment]
Ah, sorry! Updated.

**Comment by takezoe** [comment]
Also updated the commit message!

**Pull request closed without merging**
