### PR TITLE
[MINOR] Code refactor / cleanup

### PR DESCRIPTION
**Pull request by jaceklaskowski**
## Description

- Mostly minor changes (_refactoring_) to improve code readability (and ease reviewing the codebase)
- Typo fixes
- Doc and scaladoc fixes

## How was this patch tested?

`build/sbt clean package test:compile`. Waiting for the repo build to execute tests.

## Does this PR introduce _any_ user-facing changes?

No

### CODE REVIEW

**Comment by jaceklaskowski** [comment]
Ouch..."Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/t/tcltk-defaults/tk-dev_8.6.9+1_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 52.252.75.106 80]" 👎 

Any idea how to fix it? /cc @scottsand-db

**Comment by jaceklaskowski** [comment]
Yay! All checks have passed! 💪

**Comment by jaceklaskowski** [comment]
@vkorukanti @scottsand-db Mind looking at this PR (and perhaps approve it too)? 🙏

**Comment by scottsand-db** [comment]
> 

This issue seems to have resolved itself, no?

**Comment by scottsand-db** [comment]
Hi @jaceklaskowski ... with so many files being changed, I'd find it a little hard to review this PR. Much like with this other PR, https://github.com/delta-io/delta/pull/1193, which also changed a lot of files, do you think you could split this up into multiple PRs, please? Say .. 3 PRs, 10 files each, would make it a lot easier.

**Comment by jaceklaskowski** [comment]
Sure. Whatever works best for the project and the reviewers! 👍

**Comment by scottsand-db** [comment]
Thanks! With that, I'll close this PR. Cheers!

**Pull request closed without merging**
