### PR TITLE
[Docs][Process] Fix table of RFCs

### PR DESCRIPTION
**Pull request by felipepessoto**
#### Which Delta project/connector is this regarding?
- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [X] Other (fill in here)

## Description
Fix link to type widening and add managed commits to the list.

## How was this patch tested?
N/A

## Does this PR introduce _any_ user-facing changes?
No

### CODE REVIEW

**Comment by felipepessoto** [comment]
@prakharjain09, @johanl-db

**Review by johanl-db — APPROVED** [review]

**Comment by felipepessoto** [comment]
Rebased to fix conflict

**Comment by felipepessoto** [comment]
@allisonport-db could you help with merge?

**Comment by felipepessoto** [comment]
Fix included in https://github.com/delta-io/delta/pull/2683

**Pull request closed without merging**
