### PR TITLE
Add missing fields in the RemoveFile of the protocol specification

### PR DESCRIPTION
**Pull request by fvaleye**
Add missing fields in the RemoveFile of the protocol specification

### CODE REVIEW

**Comment by rahulsmahadev** [comment]
Thank you for doing this LGTM!

**Review by rahulsmahadev — APPROVED** [review]

**Comment by dengsh12** [comment]
Hey @fvaleye. We wonder if there are some specific reason `extendedFileMetadata` requires `tags`(seems not actually needed)? For context https://github.com/delta-io/delta/pull/7496 we are considering remove the requirement

**Comment by fvaleye** [comment]
Hey @dengsh12 👋,

No specific reason: this change was made by aligning `PROTOCOL.md` with the codebase.

While working on [delta-rs](https://github.com/delta-io/delta-rs) to support `extendedFileMetadata`, it was just to support the new field, and nothing depends on `tags` being present, at least on the delta-rs side I know of. 

So, I think it's safe to remove it!

**Comment by dengsh12** [comment]
@fvaleye Thanks for reply! 
> No specific reason: this change was made by aligning PROTOCOL.md with the codebase.

Aha, wonder what's the specific part in the codebase the change was trying to align? I took a look into git history, seems the code at that time doesn't really require `tags` for `extendedFileMetadata`? Just want to double check if I'm missing sth😜.

**Comment by fvaleye** [comment]
> @fvaleye Thanks for reply!
> 
> > No specific reason: this change was made by aligning PROTOCOL.md with the codebase.
> 
> Aha, wonder what's the specific part in the codebase the change was trying to align? I took a look into git history, seems the code at that time doesn't really require `tags` for `extendedFileMetadata`? Just want to double check if I'm missing sth😜.

Not used, that's why, it should be fine 👍

**Comment by dengsh12** [comment]
>Not used, that's why, it should be fine 👍

Hey @fvaleye,  would you mind stamping the protocol change? Thanks! https://github.com/delta-io/delta/pull/7496

**Pull request closed without merging**
