### PR TITLE
[WIP] Add docker/binder resources and content for quickstart and other hands-on content

### PR DESCRIPTION
**Pull request by baumanab**
- Add a folder, dockerfile, and other content for use with Delta Lake quickstart and current/future hands-on content.  
- add a binder folder with a dockerfile and instructions as a convenience resource serving the same purpose as the dockerfile mentioned above  to test the binder deployment, use the following link [Binder](https://mybinder.org/v2/gh/baumanab/delta/feature-binder_quickstart)
- This request is related to and dependent on #1033

### CODE REVIEW

**Comment by dennyglee** [comment]
Thanks @baumanab - will review this shortly!

**Comment by dennyglee** [comment]
Thanks @baumanab!  Wondering if you could update this to leverage the upcoming Spark docker per [SPIP: Support Docker Official Image for Spark](https://docs.google.com/document/d/1nN-pKuvt-amUcrkTvYAQ-bJBgtsWb9nAkNoVNRM2S2o/edit#heading=h.nqyzx5gvu8rl).

**Comment by baumanab** [comment]
I will try using the :latest example image as the base image for the build.

**Comment by baumanab** [comment]
@dennyglee I'm experimenting with this now

**Comment by baumanab** [comment]
@dennyglee I had success with a simplified version (was able to remove spark install from source) of https://github.com/baumanab/delta/blob/feature-binder_quickstart/quickstart_containers/Dockerfile_quickStart, leveraging https://hub.docker.com/r/yikunkero/spark/tags the python version of quickstart (using the python interpreter) but some basic failures executing in code in the pyspark and scala shells when leveraging the delta package (the fails do not occur when I exclude the package from the shell instantiation).  I do think making this work is feasible.  Once it is working with cli/shells we will need to settle on a strategy for a notebook interface (ie integrate it, spin up a stack where notebook runs on driver/gateway, etc).  How would you like to proceed?

**Comment by baumanab** [comment]
@dennyglee update on this.  I'm now able to build an image using https://hub.docker.com/r/yikunkero/spark/tags images as base followed by a delta 2.1.0 install stage, to get this quickstart https://docs.delta.io/latest/quick-start.html to work (python, pyspark shell, scala shell).  It should be pretty straight forward to create an official "delta" image using the same pattern.  This just leaves the question of "how do we provide a notebook interface" which is more of a design/strategy consideration.  The strategy will inform the technical approach.  My recommendationn for a quickstart would be an integrated approach (use a multi-stage build and burn it all into one image).  My recommendation beyond the quickstart would be to use a service stack that seperates interface (notebook driver) from compute.  Please let me know how you would like to proceed.

**Comment by baumanab** [comment]
@dennyglee I made some attempts that getting this to work with an integrated jupyterlab/notebook.  typical spark operations work fine, but it looks like there are some failures to find methods (possibly not finding delta jars) for using delta.  for example `data.write.format('parquet').save('somePath')` works fine, but when the format is changed to delta, it does not.  I have a feeling this will be straight-forward to resolve if there are a few sets of eyes on the issue.

**Comment by baumanab** [comment]
@dennyglee I figured out what the issue is, it is straightforward to resolve, and I can create a simplified dockerfile that leverages the upcoming official image (using latest here https://hub.docker.com/r/yikunkero/spark/tags as an example).

Should we scrap this PR and start over?

**Comment by baumanab** [comment]
> Yes, I agree with your assessment @baumanab - thanks for diving into all of this, eh?! Up for creating a new PR and then we'll close out this one?

Yes, I should have a new PR by Monday morning.  I just finished what is likely to be our final dockerfile and startup script for this stage, leveraging the official spark container examples.  Now I just need to cleanup and create the PR.

**Comment by baumanab** [comment]
@dennyglee this has been replaced by #1424 I included the docker quickstart work but excluded the binder work.  Combining them was unintentional and muddled review etc.  I will update the binder files and include it as a seperate PR

**Comment by dennyglee** [comment]
thanks @baumanab - closing out this PR.  thanks!

**Pull request closed without merging**
