### PR TITLE
[Spark] Support enable Delta Uniform on tables with DV supported but not present - part1 refactor

### PR DESCRIPTION
**Pull request by lzlfred**
#### Which Delta project/connector is this regarding?

- [x] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

## Description

Support enable Delta Uniform on tables with DV enabled but not present. Note this is mainly a refactor and the actual logic change will come later. 

## How was this patch tested?

Unit test

## Does this PR introduce _any_ user-facing changes?

No

### CODE REVIEW

**Comment by tdas** [comment]
This is great! 
It would be good backport this to the 3.0 branch as well.

**Comment by tdas** [comment]
This needs a unit test!

**Comment by lzlfred** [comment]
@tdas I just rename this as a refactor only. The actual behavior change will come in a later PR.

**Review by allisonport-db — APPROVED** [review]
LGTM

**Pull request closed without merging**
