### PR TITLE
Delta README updates

### PR DESCRIPTION
**Pull request by alexott**
- fix grammar
- use 0.8.0 as the latest version in README

### CODE REVIEW

**Review by zsxwing — APPROVED** [review]
LGTM. Thanks!

**Comment by alexott** [comment]
@zsxwing btw, should we change to the GitHub actions for CI, taking into account recent changes in CircleCI?

**Comment by zsxwing** [comment]
@alexott what changes in CircleCI? Do you know if it's easy to migrate to GitHub Actions?

**Comment by alexott** [comment]
there were changes in how they handle OSS projects, migrating all to .com from .org, I also see very slow jobs - like, this PR was in the queue for several hours, etc.  I'll try to migrate to GH actions, and submit another PR

**Comment by alexott** [comment]
Sorry, I mixed up - it was not circle-ci, but travis-ci...

**Pull request closed without merging**
