### PR TITLE
Update PowerBI Connector - fixes and restructuring

### PR DESCRIPTION
**Pull request by gbrueckl**
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [x] Other (PowerBI)

## Description
This PR resolves [issue #1978](https://github.com/delta-io/delta/issues/1978).
During the restructuring of the project, I also fixed some other minor bugs that no one found yet 
if possible, changed my tests to use the Golden Tables instead of Delta Lake tables residing on my blob stores which partially required authentication

## How was this patch tested?
Tested with a set of Golden Tables from https://github.com/delta-io/delta/tree/master/connectors/golden-tables/src/main/resources/golden`

## Does this PR introduce _any_ user-facing changes?
No

### CODE REVIEW

**Comment by dominikpeter** [comment]
Thanks a lot. I can test it on my datasets as well if you like? Also I will close my previous PR.

By the way. The function is immensely valuable for us. Thanks a lot for it 👍

**Comment by gbrueckl** [comment]
I also tested it locally on the dataset you provided - it works :)

**Comment by dominikpeter** [comment]
I tried to use this version. However, I still have duplicates.

I compared my fix with your version:

[DeltaFunctionTest.zip](https://github.com/delta-io/delta/files/12777370/DeltaFunctionTest.zip)


Maybe I am just stupid and doing something wrong 😊


I am using this version [fn_ReadDeltaTable](https://raw.githubusercontent.com/delta-io/delta/7dd9fc94395cbb906d8f70d1a217807b2a02ba63/connectors/powerbi/fn_ReadDeltaTable.pq)

**Comment by gbrueckl** [comment]
no, you were right, I also forgot to add the final code to the fn_ReadDeltaTable.pq file 🙈

**Comment by dominikpeter** [comment]
I tested it again. Now it looks good 😊.

Can someone merge this PR?

**Review by vkorukanti — APPROVED** [review]

**Pull request merged**
