### PR TITLE
Create PyPI release for python

### PR DESCRIPTION
**Pull request by nicktgr15**
Hello,

This is related to issue #282.

With this PR:
- A setup.py file is added. 
- Circleci workflow is updated to release the package on PyPI when a tag starting with `v` is created.

Need to address the following:
- Get a username and password for PyPI. The username will be added in config.yml (`<username>`), whereas the password will be stored in `$PYPI_PASSWORD` env variable in circleci. 
- Review the metadata in setup.py and decide what the `author` and `author_email` values should be. I also used `delta.io` as the package name since `delta` was used already. 
- Added `pyspark` as an install dependency (i.e. will get installed when you do `pip install delta.io`) but whether it needs to stay there is open for discussion.

### CODE REVIEW

**Comment by databricks-cla-assistant** [comment]
[CLA assistant check](https://cla.dev.databricks.com/delta-io/delta?pullRequest=353) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.databricks.com/delta-io/delta?pullRequest=353) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dev.databricks.com/check/delta-io/delta?pullRequest=353) it.</sub>

**Comment by tdas** [comment]
this is awesome. i am unfortunately not knowledgeable about how to do pypi release, so i have do some homework myself to learn more about it.

**Comment by nicktgr15** [comment]
Hello @tdas, afaict all you need to do is create an account for delta-io on PyPI https://pypi.org/account/register/ and store the password ($PYPI_PASSWORD) as a secret in circleci. Also I think it makes more sense to rename the package from `delta.io` to `delta-io`.

**Comment by tdas** [comment]
Hey @nicktgr15 I was doing my homework learning about pypi releases and I was wondering 
1. Have you tested this out using test.pypi.org? At the first glance, I am not sure how this script would work. It seems to only package the `python` directory and not the delta JARs that are needed for python code to work. Fu

2. Furthermore, if you have tested with test.pypi.org (or manually), have you made sure that it works with pyspark? That is, pyspark is able to correctly find the python class and the JARs?

**Comment by nfx** [comment]
subscribing to know when it's released...

**Comment by nicktgr15** [comment]
Hello @tdas, 

Created a release under https://test.pypi.org/project/delta.io/0.5.0/ using `twine upload --repository-url https://test.pypi.org/legacy/ dist/*`. The artifacts under `dist` are created using `python setup.py bdist_wheel` and  `python setup.py sdist`. (these steps are already available in the circleci conf file on the PR). 

I have some pyspark tests where I'm using `delta` and I was able to pip install the dependency from test.pypi.org `pip install -i https://test.pypi.org/simple/ delta.io==0.5.0` and run them without issues.  Note that in my spark conf during the tests I'm using `.set("spark.jars.packages", "io.delta:delta-core_2.11:0.5.0")`.

Hope the above helps.

**Comment by tdas** [comment]
@nicktgr15 That's awesome! Thank you for testing it out comprehensively. This is cool! However, it looks like the pip installation is not self-contained as you have to add `.set("spark.jars.packages", "io.delta:delta-core_2.11:0.5.0")`. What this is doing is it's getting the python files only from the pip installation of delta, and then getting the jar files from the maven release (setting the cof to `io.delta:delta-core_2.11:0.5.0` is doing exactly that).

This is quite suboptimal. The point of any such package installations systems is that they are self-contained and automatically handles all its dependencies without requiring the user to configure additional things. This, unfortunately, is not self-contained.

In fact, this can be a recipe for disaster. One can easily misconfigure their project to cause a mismatch between the python version and the jar version. E.g., someone runs their python project on a different system with a different version of pip delta installed without remembering to update the SparkConf accordingly. Such situations can be very hard to debug. In contrast, the current solution with `pyspark --packages io.delta:delta-core_2.11:0.5.0` is self-contained as this one setting/command-line arg will take care of configuring both python and java, thus avoiding any scope of version mismatch.

Now I don't have a very good solution off the top of my head to fix this. I know that jars can be packaged insides wheels (pyspark does that in its pypi packaging). However, the real challenge is packaging the jar such that after pip installation, pyspark is able to find those jars and automatically put them in the classpath for the spark JVM process. There may exist other projects that have done something like this that we can learn from, but I dont know of any.

**Comment by filipe-plutoflume** [comment]
subscribing

**Comment by nicktgr15** [comment]
Hi @tdas,

Yes, your concern makes sense.

I had a look for pyspark packages with python wrappers for scala/java libraries (there aren't many) and providing the packages/jars separately seems to be a common (bad?) practice. Examples include:

* https://github.com/JohnSnowLabs/spark-nlp, where they provide a `start()` method to set the `spark.jars.packages` conf param https://github.com/JohnSnowLabs/spark-nlp/blob/master/python/sparknlp/__init__.py#L40 or they suggest to create the session manually https://github.com/JohnSnowLabs/spark-nlp/blame/master/README.md#L247.
* https://github.com/locationtech-labs/geopyspark, in this case they also have a config init method https://github.com/locationtech-labs/geopyspark/blob/master/geopyspark/__init__.py#L118 where `spark.jars` is getting set. The jars are downloaded separately. (this project is not under active development)

Apart from the above thought, I realised that there's a workaround to solve this problem, without releasing a pypi package. e.g. https://github.com/Azure/mmlspark 
```import pyspark
spark = pyspark.sql.SparkSession.builder.appName("MyApp") \
            .config("spark.jars.packages", "com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1") \
            .config("spark.jars.repositories", "https://mmlspark.azureedge.net/maven") \
            .getOrCreate()
import mmlspark
```
were the session is created first and afterwards you can import `mmlspark`. 

In my case with delta (when using `spark.jars.packages`) the following doesn't work because `delta` is not installed

```
from delta.tables import DeltaTable

def delta_table_exists(path):  
    return DeltaTable.isDeltaTable(identifier=path, sparkSession=get_spark_session())
```

however, the following works fine (because the delta import is executed inside the spark session). 
```
def delta_table_exists(path):
    from delta.tables import DeltaTable
    return DeltaTable.isDeltaTable(identifier=path, sparkSession=get_spark_session())
```
Of course static code analysis doesn't work very well with this approach.

**Comment by tdas** [comment]
This is a great find and definitely worth documenting! Can you update the original issue #282 with this alternative? I will try to add this to the online docs as well, maybe in the quick-start guide.

In addition, from your survey, it seems like there is no clean solution for making it work with pypi packaging. And this import-after-session-creation seems to be a much cleaner approach. In that case, I am inclined to drop this pypi packaging attempt for now. 

Nonetheless, thank you very much for investigating!!!

**Comment by Lukas012** [comment]
Sad, that this seems so complicated. In the current situation: is there any possibility that static code analyzers (e.g. My IDE pycharm or Pylint) can recognize that
```
from delta.tables import DeltaTable
```
is a valid import and I can use autocompletion etc.?

**Comment by zsxwing** [comment]
This has been done by https://github.com/delta-io/delta/commit/98c66a64d7ab60fc27ba790d7ef3df82bd76c3cb

**Pull request closed without merging**
