### PR TITLE
Optimize imports

### PR DESCRIPTION
**Pull request by AFFogarty**
I noticed that the Scala imports seem to be inconsistently formatted across files.

For this PR, I ran IntelliJ's "Optimize Imports" command which has cleaned up the imports and made the formatting consistent.

cc: @suhsteve @imback82 @rapoth

### CODE REVIEW

**Comment by databricks-cla-assistant** [comment]
[CLA assistant check](https://cla.dev.databricks.com/delta-io/delta?pullRequest=297) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.databricks.com/delta-io/delta?pullRequest=297) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dev.databricks.com/check/delta-io/delta?pullRequest=297) it.</sub>

**Comment by chetkhatri** [comment]
@AFFogarty You haven't signed the `Contributor License Agreement`.

**Comment by mukulmurthy** [comment]
> @AFFogarty You haven't signed the `Contributor License Agreement`.

As part of moving to Linux Foundation I think we don't need that. @marmbrus , can you confirm / how do we remove it?

**Comment by AFFogarty** [comment]
Resolved merge conflicts and added test directories.

**Comment by zsxwing** [comment]
Closing this out of date PR. It's better to clean imports when touching a file rather than a big clean PR.

**Pull request closed without merging**
