### PR TITLE
Migrate deltalog

### PR DESCRIPTION
**Pull request by MrPowers**

### CODE REVIEW

**Comment by MrPowers** [comment]
This PR is to explore what Spark API would need to get opened up to move `DeltaLog` to the `io.delta` package.  We started the conversation on this issue: https://github.com/delta-io/delta/issues/204

**Comment by tdas** [comment]
I dont think it makes sense to move all of delta into the io.delta package. In fact some of the functionality of apache sql that we internally use requires it to be inside org.apache.spark.sql. That why we decide to keep most of delta stuff within org.apache.spark leaving only the public APIs into io.delta. 

As per issue #204, we should reduce the top-level packages by just moving the `test.com.databricks` to `test.io.delta`. That should just touch java test files.

**Comment by databricks-cla-assistant** [comment]
[CLA assistant check](https://cla.dev.databricks.com/delta-io/delta?pullRequest=210) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.databricks.com/delta-io/delta?pullRequest=210) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dev.databricks.com/check/delta-io/delta?pullRequest=210) it.</sub>

**Comment by zsxwing** [comment]
Closing this stale PR. We prefer to avoid such huge changes with little benefits.

**Pull request closed without merging**
