### PR TITLE
Update README.md version to 0.5.0

### PR DESCRIPTION
**Pull request by hddong**
update 0.4.0 to latest version

### CODE REVIEW

**Comment by databricks-cla-assistant** [comment]
[CLA assistant check](https://cla.dev.databricks.com/delta-io/delta?pullRequest=279) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.databricks.com/delta-io/delta?pullRequest=279) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dev.databricks.com/check/delta-io/delta?pullRequest=279) it.</sub>

**Comment by hddong** [comment]
@mukulmurthy thanks, i will close this pr.

**Comment by mukulmurthy** [comment]
Previous changes updated the other two but not examples/README.md. Can we still merge your PR to get that change?

**Comment by hddong** [comment]
@mukulmurthy sure, I had delete change of README.md which may cause conflict.

**Pull request closed without merging**
