### PR TITLE
Branch 1.0.1 candidate

### PR DESCRIPTION
**Pull request by scottsand-db**
Backport a variety of minor bug fixes and improvements to branch-1.0.

- https://github.com/delta-io/delta/commit/59aa330c403f8a71b3eef0e90bd61cd54aab108c
- https://github.com/delta-io/delta/commit/104e2a472b5a0a5c718c42ac14ac8b851a1a7fe8
- https://github.com/delta-io/delta/commit/7a3f1e8ec626e80880d524c2b897a969c8b4d63a
- https://github.com/delta-io/delta/commit/43d14226cc802d721d1683495cdc8511acf460a1
- https://github.com/delta-io/delta/commit/c586f9a7374923867c36f61df4ed133725c8df2c
- https://github.com/delta-io/delta/commit/95e90763fd9f54df8880911b28b97b023a485d5f
- https://github.com/delta-io/delta/pull/856/commits/ee5d31f52fadc03d46d7ffe5010e7b3ffe73baf1 // enable github actions to run tests
- https://github.com/delta-io/delta/commit/4359484368b4a06c32b663826ac60bf12d9e8025
- https://github.com/delta-io/delta/commit/4bee7ae50c50299cdea54ed3afeb59effa0f0790 // fix actions sbt download
- https://github.com/delta-io/delta/commit/86bbe9905ebf8c57f5bf5078a5d18ad2b5081abe // fix actions sbt download

### CODE REVIEW

**Comment by TomerYacov** [comment]
hi guys! there is a critical bug fix here that we are exposed to in our production env.

[7a3f1e8](https://github.com/delta-io/delta/commit/7a3f1e8ec626e80880d524c2b897a969c8b4d63a)

**Comment by zsxwing** [comment]
@allisonport-db you may need to check history of https://github.com/delta-io/delta/commits/master/.github/workflows/test.yaml and cherry-pick some fixes for GitHub Actions to branch-1.0 as well

**Comment by zsxwing** [comment]
One small bug fix to cherry-pick: https://github.com/delta-io/delta/commit/4359484368b4a06c32b663826ac60bf12d9e8025

**Comment by allisonport-db** [comment]
> @allisonport-db you may need to check history of https://github.com/delta-io/delta/commits/master/.github/workflows/test.yaml and cherry-pick some fixes for GitHub Actions to branch-1.0 as well

I looked through the history and none of the commits seem directly related to 

```
Run pipenv run python run-tests.py 
Using /opt/hostedtoolcache/Java_Zulu_jdk/8.0.322-[6](https://github.com/delta-io/delta/runs/5059460025?check_suite_focus=true#step:6:6)/x64 as default JAVA_HOME.
Note, this will be overridden by -java-home if it is set.
Attempting to fetch sbt
Our attempt to download sbt locally to build/sbt-launch-0.13.18.jar failed. Please install sbt manually from http://www.scala-sbt.org/
##### Running SBT tests #####
Traceback (most recent call last):
  File "run-tests.py", line [7](https://github.com/delta-io/delta/runs/5059460025?check_suite_focus=true#step:6:7)4, in <module>
    run_sbt_tests(root_dir)
  File "run-tests.py", line 27, in run_sbt_tests
    run_cmd([sbt_path, "clean", "test"], stream_output=True)
  File "run-tests.py", line 46, in run_cmd
    raise Exception("Non-zero exitcode: %s" % (exit_code))
Exception: Non-zero exitcode: 255
Error: Process completed with exit code 1.
```

This is an issue with the cache, right? I don't remember how we resolved this before.

**Comment by zsxwing** [comment]
@allisonport-db we need to cherry-pick 
- https://github.com/delta-io/delta/commit/4bee7ae50c50299cdea54ed3afeb59effa0f0790
- https://github.com/delta-io/delta/commit/86bbe9905ebf8c57f5bf5078a5d18ad2b5081abe

to fix the SBT download

By the way, when you use git cherry-pick, you can add `-x` such as `git cherry-pick -x 86bbe9905ebf8c57f5bf5078a5d18ad2b5081abe`. It will add `(cherry picked from commit 86bbe9905ebf8c57f5bf5078a5d18ad2b5081abe)` to the commit message and make us easy to locate the commit in master in branch-1.0.

**Comment by zsxwing** [comment]
@tdas that commit should be safe. We use `spark.sessionState.newHadoopConf` to write json files. If using `spark.sessionState.newHadoopConf` to write checkpoint files doesn't work, json file writing will be broken as well

**Review by zsxwing — APPROVED** [review]
The commit list looks good to me

**Pull request merged**
