### PR TITLE
Implement WHEN NOT MATCHED BY SOURCE functionality

### PR DESCRIPTION
**Pull request by seddonm1**
Currently the API of DeltaLake follows the `MERGE` behavior implemented in multiple SQL engines. This behavior does not expose a method for deleting records from the target that no longer exist in the source. [Microsoft SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/merge-transact-sql?view=sql-server-ver15) adds a more advanced `MERGE` behavior which allows the specification of multiple `WHEN NOT MATCHED` statements specifying either `SOURCE` or `TARGET`.

```sql
MERGE
    [ TOP ( expression ) [ PERCENT ] ]
    [ INTO ] <target_table> [ WITH ( <merge_hint> ) ] [ [ AS ] table_alias ]  
    USING <table_source>
    ON <merge_search_condition>  
    [ WHEN MATCHED [ AND <clause_search_condition> ]  
        THEN <merge_matched> ] [ ...n ]  
    [ WHEN NOT MATCHED [ BY TARGET ] [ AND <clause_search_condition> ]  
        THEN <merge_not_matched> ]  
    [ WHEN NOT MATCHED BY SOURCE [ AND <clause_search_condition> ]  
        THEN <merge_matched> ] [ ...n ]  
```

DeltaLake implicitly implements the `WHEN NOT MATCHED BY TARGET` but currently does not have a way of specifying `WHEN NOT MATCHED BY SOURCE`. This PR implements the `WHEN NOT MATCHED BY SOURCE` capability whilst retaining the existing `whenNotMatched` API. This means all existing code remains unchanged.

In doing so the logic for identifying files to be rewritten has been updated as previously all files impacted by the `join condition` were rewritten whether the data changed or not. This PR changes that behavior to only rewrite files actually changed by the `MERGE` statement which means much less data is rewritten if a dataset is only changing by a small number of rows each `MERGE` which is beneficial to both runtime and disk usage. The use case for this is applying table snapshots as incoming `SOURCE` record sets to a target existing table 'delta' snapshot and only writing the changes - giving a way to efficiently time travel through table versions over time without consuming disk for unchanged data.

### CODE REVIEW

**Comment by jose-torres** [comment]
Going forward, we're trying to align Delta Lake's MERGE with the Apache Spark MERGE that's planned to be released in the next Spark version. I'd recommend adding this new syntax to Spark first (https://github.com/apache/spark).

**Comment by seddonm1** [comment]
thanks @jose-torres 

I have looked at the spark 3.0 code and see they have also implemented the limited SQL functionality (https://github.com/apache/spark/blob/8b01473e8bffe349b1ed993b61420d7d68896cd8/sql/core/src/test/scala/org/apache/spark/sql/execution/command/PlanResolutionSuite.scala)

```sql
MERGE INTO $target AS target
USING $source AS source
ON target.i = source.i
WHEN MATCHED AND (target.s='delete') THEN DELETE
WHEN MATCHED AND (target.s='update') THEN UPDATE SET *
WHEN NOT MATCHED AND (source.s='insert') THEN INSERT *
```

This PR does not actually expose a SQL interface to `WHEN NOT MATCHED BY SOURCE` but implements `whenNotMatched` as an alias of `whenNotMatchedByTarget` for existing behavior which matches the Spark SQL spec above. The big difference is adding the `whenNotMatchedBySource` functionality which could be added to Spark core but in the meantime it could be implemented in DeltaLake at a Scala level only for the people who need this capability.

Secondly the rewritten merge behavior reduces unnecessary writes significantly when doing `MERGE` with datasets with minor changes (like applying daily table snapshots from a source system).

**Comment by jose-torres** [comment]
That makes sense, and I can definitely see the value in having this new syntax, but it'll have to be added to Spark before we can support it in Delta Lake.

**Comment by seddonm1** [comment]
Ok will close this for now.

**Pull request closed without merging**
