### PR TITLE
Add required/optional column to transaction and protocol action description

### PR DESCRIPTION
**Pull request by jkylling**
## Description

Adds a optional/required column to the tables describing the fields of transaction and protocol actions, similar to what we have for the other actions. This clarifies which fields of the transactions and protocol actions are required or optional.

### CODE REVIEW

**Comment by tdas** [comment]
@ryan-johnson-databricks could you take a look?

**Review by ryan-johnson-databricks — COMMENTED** [review]
LGTM!

**Review by ryan-johnson-databricks — APPROVED** [review]

**Comment by ryan-johnson-databricks** [comment]
@jkylling I'm getting this error report from an internal tool:
> User with name 'Jonas Irgens Kylling' has a private email 'jkylling@users.noreply.github.com'.
> This is against Linux Foundation guidelines.
> Please provide a public email address for this contributor.

**Comment by tdas** [comment]
We are testing out a tool that verifies whether the github handle is associated with a public email with which they can be contacted if needed (thats the Linux Foundation guideline). Could you please check if your gmail address is publicly visible in your github profile? 

thanks for you patience.

**Comment by jkylling** [comment]
No worries, I've made my email public on my profile now.

**Pull request closed without merging**
