### PR TITLE
Upgrade Hadoop version to 3.3.4

### LINKED ISSUE #1935: [BUG][Spark] Hadoop version is outdated and incompatible with Spark 3.3+
#### Which Delta project/connector is this regarding?
- [X] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

### Describe the problem
Spark Delta references Hadoop version 3.3.1, this version is used by Spark 3.2.
The biggest problem is Hadoop 3.3.2 has a breaking change that affect us, we are compiling against a version, and at runtime it will fail.

I believe this PR (https://github.com/delta-io/delta/pull/1688) fix it, but I'm opening the issue to further discussion.

### Environment information

* Delta Lake version: 2.4.0
* Spark version: 3.4.1
* Scala version: 2.12

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [X] No. I cannot contribute a bug fix at this time.

### PR DESCRIPTION
**Pull request by rbushri**
#### Which Delta project/connector is this regarding?

- [X] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

## Description
Upgrade Hadoop version to 3.3.4 to alain with spark [3.5.0](https://github.com/apache/spark/blob/v3.5.0/pom.xml#L125) version.

Fix #1935.

## How was this patch tested?
Unit test - SUCCEEDED

## Does this PR introduce _any_ user-facing changes?
No

### CODE REVIEW

**Comment by felipepessoto** [comment]
@rbushri this is great. I think this is currently not working in 3.0.0 and also 2.4.0, since Spark 3.4 also uses this Hadoop version.

Have you synced with @scottsand-db? He has a PR open opened [1688](https://github.com/delta-io/delta/pull/1688), with additional changes.

Thanks. Happy to see this fixed.

**Comment by rbushri** [comment]
> @rbushri this is great. I think this is currently not working in 3.0.0 and also 2.4.0, since Spark 3.4 also uses this Hadoop version.
> 
> Have you synced with @scottsand-db? He has a PR open opened [1688](https://github.com/delta-io/delta/pull/1688), with additional changes.
> 
> Thanks. Happy to see this fixed.

I reviewed @scottsand-db's PR, and the additional changes involve adding an info log and making small cosmetic changes. I'm uncertain if these should be included in this PR since they're not directly related to the Hadoop version. However, if you think they should be included, I'll add them.

**Comment by felipepessoto** [comment]
It is good to me as is

**Comment by felipepessoto** [comment]
Could you add a "Fix #1935" to the PR description?

Any plans to merge this before 3.1 cut?

**Comment by rbushri** [comment]
> Could you add a "Fix #1935" to the PR description?
> 
> Any plans to merge this before 3.1 cut?

1) done.
2) I hope so too.

**Review by scottsand-db — APPROVED** [review]

**Pull request closed without merging**
