### PR TITLE
Adding support for GCS

### PR DESCRIPTION
**Pull request by ranu010101**
Adding support for Google Cloud Storage(GCS) as Delta Storage by introducing GcsLogStore.

This PR addresses [issue #294][1]. File creation is an all-or-nothing approach to achieve atomicity and uses Gcs [preconditions][2] to avoid race conditions among multiple writers/drivers. This implementation relies on gcs-connector to provide necessary `FileSystem` implementations. This has been tested on a Google Dataproc cluster. 

#### GcsLogStore requirements

1. spark.delta.logStore.class=org.apache.spark.sql.delta.storage.GcsLogStore 
2. Include gcs-connector in classpath. The Cloud Storage connector is automatically installed on Dataproc clusters.

#### Usage

```
TABLE_LOCATION = 'gs://ranuvikram-test/test/delta-table'

# Write data to table.
data = spark.range(5, 10)
data.write.format("delta").mode("append").save(TABLE_LOCATION)

# Read data from table.
df = spark.read.format("delta").load(TABLE_LOCATION)
df.show()
```

[1]: https://github.com/delta-io/delta/issues/294
[2]: https://cloud.google.com/storage/docs/generations-preconditions#_Preconditions

### CODE REVIEW

**Comment by ranu010101** [comment]
@marmbrus @rxin @mateiz what is the process for getting this reviewed? Let me know if anything is required from my side.

**Comment by ranu010101** [comment]
@zsxwing Is there any way we can make progress on this?

**Review by medb — APPROVED** [review]

**Comment by walmaaoui** [comment]
Hello @ranu010101, I have a question as a user of Delta and GCP, what is the added value of this PR please? Because we already use Delta, GCS and Dataproc for a while now and we didn't had any issue with it. We dont specify any `spark.delta.logStore.class`, I dont know which one is used under hood.

**Comment by tdas** [comment]
Hello @ranu010101 Our apologies for sitting on the PR for so long. We wanted to figure out what is the best way to integrate slightly less battle-tested features into our repo, and we finally figured it out. We have converted our repo to a multi-module SBT project so that we can add a contribs sub-module (mapping to a new maven release artifacts beyond delta-contribs). So we can add this log store to that module. Are you still interested in contributing to this feature?

**Comment by tdas** [comment]
@walmaaoui Valid question. The default HDFSLogStore will work well for reads, but for writes there is a slight chance of failure on concurrent writes without overwrites. Basically when there are two concurrent attempts to write the same file, only one of them is sure to win. But the other one is expected to throw FileAlreadyExistsException (and we retry at a higher level). However, there is a small chance that it throws a different exception, which can cause the write operations to unnecessarily fail.

**Comment by ranu010101** [comment]
Hi @tdas. Sure we can add this LogStore to the contribs module. I can keep supporting this feature by working on any relevant issues or updating if required.

**Comment by tdas** [comment]
awesome! thank you so much. others have added similar LogStores in the contribs module. Please follow the pattern this [PR](https://github.com/delta-io/delta/pull/302) has done. Except the contrib module is already added, so you just have to add your LogStore and corresponding. LogStoreSuite in the right place.

**Comment by tdas** [comment]
@ranu010101 please update the PR whenever you can.

**Comment by tdas** [comment]
@ranu010101 do you have time to update the PR?

**Comment by tdas** [comment]
Ping! any update @ranu010101

**Comment by tdas** [comment]
If you dont have the time, do you mind i do the necessary refactoring.

**Comment by ranu010101** [comment]
Sure that will be very welcome. Thanks in advance.

**Comment by tdas** [comment]
By the Linux foundation rules, we need a public email address for contribution. If you are contributing as a Google employee, then do you have a google email address in the git commit? Or any other public email address? 

Make sure that the email address you give is tied to your github account (so that it links up and your github account gets the credit).

**Comment by ranu010101** [comment]
I've updated the email address associated with the commit.

**Comment by ranu010101** [comment]
Thanks @tdas

**Pull request closed without merging**
