### PR TITLE
HDFSLogStore.java Fix catch - throw exception mismatch

### LINKED ISSUE #978: HDFSLogStore.java catch and throw exception mismatch
I noticed that in this below code
https://github.com/delta-io/delta/blob/master/storage/src/main/java/io/delta/storage/HDFSLogStore.java#L130
```java
catch (org.apache.hadoop.fs.FileAlreadyExistsException e) {
                throw new FileNotFoundException(path.toString());
}
```
The catch block catches `FileAlreadyExistsException` but throws `FileNotFoundException`.
I think it should also throws `FileAlreadyExistsException`. Do I misunderstand the situation there?

### PR DESCRIPTION
**Pull request by PhVHoang**
Resolve #978 

Signed-off-by: Pham Hoang <a2k40pbc@gmail.com>

### CODE REVIEW

**Comment by scottsand-db** [comment]
Good catch! Thanks!

**Comment by scottsand-db** [comment]
@zsxwing looking

**Comment by scottsand-db** [comment]
@zsxwing 

It is hard to test that `fc.rename(tempPath, path, renameOpt)` throws `FileAlreadyExistsException`. It will only throw is `overwrite=false` and `path` file already exists.

Before we get to this line of code, we already perform the check

```
if (!overwrite && fc.util.exists(path)) {
      // This is needed for the tests to throw error with local file system
      throw new FileAlreadyExistsException(path.toString)
    }
```

which checks exactly that.

**Comment by scottsand-db** [comment]
I'll try and find a workaround.

**Comment by zsxwing** [comment]
> I'll try and find a workaround.

Thanks for looking at this. We can have a followup RP to create a fake file system that throws `FileAlreadyExistsException` from `rename`.

**Review by zsxwing — APPROVED** [review]

**Comment by scottsand-db** [comment]
@zsxwing created it here: https://github.com/delta-io/delta/pull/983

**Pull request closed without merging**
