### PR TITLE
Sample Delta Lake Jupyter notebook

### PR DESCRIPTION
**Pull request by dennyglee**
Here's a sample Delta Lake Jupyter notebook.  Could you please provide feedback so I can update accordingly?  Thanks!

### CODE REVIEW

**Comment by databricks-cla-assistant** [comment]
[CLA assistant check](https://cla.dev.databricks.com/delta-io/delta?pullRequest=58) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.databricks.com/delta-io/delta?pullRequest=58) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dev.databricks.com/check/delta-io/delta?pullRequest=58) it.</sub>

**Comment by dennyglee** [comment]
cc @brkyvz

**Comment by sgloutnikov** [comment]
Great sample, thanks! Would adding the notebook in .ipynb format be better as it would be interpreted and more easily viewable in GitHub?

**Comment by dennyglee** [comment]
Oh good point, sure, I can update that later today

**Comment by mukulmurthy** [comment]
Re-ping @brkyvz - looks like this kind of got dropped. Can you take another look?

**Comment by zsxwing** [comment]
Closing this as we don't need this

**Pull request closed without merging**
