### PR TITLE
[MINOR] Use deltaLog.tableExists for table availability

### PR DESCRIPTION
**Pull request by jaceklaskowski**
Signed-off-by: Jacek Laskowski <jacek@japila.pl>

### CODE REVIEW

**Review by mengtong-db — APPROVED** [review]
Thanks! LGTM.

**Comment by jaceklaskowski** [comment]
Can I have your take on this PR? @tdas @zsxwing @brkyvz

**Comment by zsxwing** [comment]
Thanks for the contribution. We are merging the PR. It may take a while as we usually merge to our internal fork first to run our entire test.

**Comment by jaceklaskowski** [comment]
Closed not merged? May I ask why? @mengtong-db

**Pull request closed without merging**
