### PR TITLE
Add PROTOCOL.md mention that schemaString is required in first Delta log entry

### PR DESCRIPTION
**Pull request by xianwill**
The existing protocol doc mentions that a metadata action is required in the first version of a table, but it does not specify required or optional fields for the metadata action. I believe _schemaString_ should be required at a minimum in the v1 delta log entry.  

This PR adds a short and sweet mention in the first paragraph of the `### Change Metadata` section to communicate that `schemaString` is required in the first `metadata` entry and transitively, the first log entry -- piggy backing on the existing mention that a `metadata` action [is required](https://github.com/delta-io/delta/blob/4277443703c5ab59a567c1e80189bbcdb7495817/PROTOCOL.md#change-metadata) in the first delta table version.

Ideally, additional optional/required/required-if specifications for `metadata` properties should be provided in the protocol doc, because as it stands, an empty `metadata` object (i.e. `metadata: {}`) is permitted by the protocol doc which is not helpful to any human or computer. With this PR, I am interested in solving for absent schema in the first table version. Unfortunately, [some projects](https://github.com/delta-io/connectors/blob/master/golden-tables/src/test/resources/golden/canonicalized-paths-normal-a/_delta_log/00000000000000000000.json) are already leveraging the under-specification. A table with no schema metadata is not useable from a reader perspective, so should not be possible to create from a writer perspective IMHO. Hopefully, this PR should discourage folks following the protocol from creating scenarios that do not include metadata schema in the first log entry.

I would like to see optional/required/required-if specifications added to the `metadata` section for all properties for v1 + n, but I cannot determine which properties fit which category other than that v1 must include `schemaString` at this time.

---

UPDATE

After realizing the full implications of the existing protocol statement that:

> Subsequent metaData actions completely overwrite the current metadata of the table.

and also grokking the required/optional mentions by @houqp - I have changed the PR content significantly. Instead of a "short and sweet mention in the first paragraph" - I have gone all in on an optional/required column in the `metadata` field table + a mention that required properties must be included in every `metadata` action.

### CODE REVIEW

**Comment by houqp** [comment]
Would like to hear other maintainers' opinions on this as well. I think we should add a `nullable`/`nullable`/`required` column to the metadata schema spec table. To me it feels like only `id` and `createdTime` should be marked as required?

**Comment by xianwill** [comment]
`format` might be another field worthy of being required in at least the first log entry as well.

**Comment by xianwill** [comment]
`format` seems like it could be required as well so that readers know how to read.

**Comment by houqp** [comment]
So two proposals here:

1. Requiring `schemaString` and `format` in the first metadata action committed to transaction log
2. Adding a new `nullable`/`optional`/`required` column to the metadata schema spec table so we can specify what fields are optional for all metadata actions in the transaction log.

**Comment by xianwill** [comment]
Thanks @houqp - your mention, plus my notice that the existing protocol doc already mentions that

> Subsequent metaData actions completely overwrite the current metadata of the table.

has changed my PR content significantly. See updates in https://github.com/delta-io/delta/pull/610/commits/f3cdf7a4f9d91115ebe7fecbcdaa5b00596adc54.

Given the existing overwrite constraint, I think this boils down to optional vs required which can be specified for each subfield of the metadata object as [rendered here](https://github.com/xianwill/delta/blob/protocol_update/PROTOCOL.md#change-metadata).

I have also added a statement to the `Change Metadata` section that states:

> Every metadata action must include required fields at a minimum.

**Comment by rtyler** [comment]
@dennyglee @marmbrus would one of you happen to know who the right reviewers might need to look at this?

**Comment by dennyglee** [comment]
Including @mengtong-db - let’s review this and validate.

**Comment by dennyglee** [comment]
Hey @xianwill - any thoughts or comments per feedback?  Thanks!

**Comment by xianwill** [comment]
@dennyglee + @zsxwing - I have made the suggested edits regarding required/optional for `createdTime` and `configuration`.

**Review by zsxwing — APPROVED** [review]
LGTM

**Pull request closed without merging**
