### PR TITLE
Bump Spark version from 3.5.0 to 3.5.2

### PR DESCRIPTION
**Pull request by nastra**
#### Which Delta project/connector is this regarding?

- [x] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

## Description

This bumps the Spark version from 3.5.0 to 3.5.2

### CODE REVIEW

**Comment by nastra** [comment]
@scottsand-db can you review this one please?

**Comment by scottsand-db** [comment]
Failed Spark 3.5.2 test: https://github.com/delta-io/delta/actions/runs/10351258969/job/28649387793?pr=3529

```
[info] - merge-metrics: delete-only with duplicates - Partitioned = false, CDF = false *** FAILED ***
[info]   The recorded metric for numTargetFilesAdded does not equal the expected value.
[info]    expected = 2 ,
[info]    But actual = 1 (DescribeDeltaHistorySuite.scala:108)
```

@c27kwan - does this relate to your changes for Spark 3.5.2?

**Comment by c27kwan** [comment]
No, it's not related. We added a new trait in Spark 3.5.2 to relax CheckAnalysis for Delta MERGE, but this trait is not yet used in Delta.

**Comment by vkorukanti** [comment]
We need a test change and update the pyspark version in tests. See the changes here: https://github.com/delta-io/delta/pull/3417/files

**Comment by nastra** [comment]
@vkorukanti I didn't realize there is https://github.com/delta-io/delta/pull/3417, so I'll close this PR in favor of https://github.com/delta-io/delta/pull/3417

**Pull request closed without merging**
