### PR TITLE
Added Python APIs for merge, update, delete

### PR DESCRIPTION
**Pull request by tdas**
- Added merge, update, delete to the Python DeltaTable class.
- Added new unit tests to test_deltatable.py.

### CODE REVIEW

**Comment by ronflomin** [comment]
Shouldn't also be a Python package?
How can we use the python api?

**Comment by tdas** [comment]
@ronflomin Python APIs will be packaged and used in the same way as the scala APIs. We will publish 0.4.0 jars to maven, the jar will contain the python files. This packaging magic is done using the [spark-packages](https://github.com/databricks/sbt-spark-package) plugin. When you will run spark-submit or pyspark using `--package io.delta:delta-core:0.4.0`, pyspark will automatically put the python classes in the 0.4.0 jar in the python path such that you will be able to simply do `from delta.tables import *` in your python code.

**Comment by ronflomin** [comment]
Sounds great.
When are you planning to release version 0.4?

**Comment by tdas** [comment]
@ronflomin end of this week, or early next week. 
https://github.com/delta-io/delta/milestone/4

**Pull request closed without merging**
