### PR TITLE
[Spark] Change Scala version to match Spark 3.4

### LINKED ISSUE #1909: [Feature Request] Scala 2.12.17
### Overview

Spark 3.4 is built with Scala 2.12.17. If there isn't anything blocking us, I think we should move to the same version.

### Motivation

The same as https://github.com/apache/spark/pull/37892

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [ ] Yes. I can contribute this feature independently.
- [X] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [ ] No. I cannot contribute this feature at this time.

### PR DESCRIPTION
**Pull request by felipepessoto**
#### Which Delta project/connector is this regarding?
- [X] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

## Description

Matches Scala version of Spark 3.4: https://github.com/apache/spark/blob/59fcecb5a59df54ecb3c675d4f3722fc72c1466e/pom.xml#L171

https://github.com/scala/scala/releases/tag/v2.12.16
https://github.com/scala/scala/releases/tag/v2.12.17

https://github.com/scala/scala/releases/tag/v2.13.6
https://github.com/scala/scala/releases/tag/v2.13.7
https://github.com/scala/scala/releases/tag/v2.13.8

Fix #1909

## Does this PR introduce _any_ user-facing changes?

Changes Scala version, which should be compatible:
"As usual for our minor releases, Scala 2.12.17 is binary-compatible with the whole Scala 2.12 series."
"As usual for our minor releases, Scala 2.13.8 is binary-compatible with the whole Scala 2.13 series."

### CODE REVIEW

**Comment by felipepessoto** [comment]
@allisonport-db, could you please review this?

**Comment by allisonport-db** [comment]
Sorry, @felipepessoto could you fix the conflicts?

**Comment by felipepessoto** [comment]
> Sorry, @felipepessoto could you fix the conflicts?

Yes, done. Thanks

**Review by allisonport-db — COMMENTED** [review]
Can you update the `connectors_test.yaml` and `kernel_test.yaml`?

**Comment by felipepessoto** [comment]
> Can you update the `connectors_test.yaml` and `kernel_test.yaml`?

Done. Also updated some new comments added in recent commits

**Comment by felipepessoto** [comment]
https://github.com/delta-io/delta/blob/011bda5b573cd3fe90975034fc578b793b941e54/connectors/build.sbt#L35-L38

and https://github.com/delta-io/delta/blob/master/connectors/examples/build.sbt

Has multiple references to Scala 2.12.8, which doesn't even match the current version in https://github.com/delta-io/delta/blob/master/build.sbt. Should we change to 2.12.17?

**Comment by felipepessoto** [comment]
@allisonport-db could you review it again?

**Review by allisonport-db — APPROVED** [review]
LGTM

**Comment by felipepessoto** [comment]
@allisonport-db I rebased it to resolve conflict, connectors/build.sbt doesn't exist anymore

**Comment by allisonport-db** [comment]
Sorry @felipepessoto could you rebase one more time :)

**Comment by felipepessoto** [comment]
@allisonport-db done

**Comment by felipepessoto** [comment]
@allisonport-db testing are passing, could you check again please?

**Comment by felipepessoto** [comment]
ping @allisonport-db. Do you plan to merge it soon? These build files constantly change and can cause new conflicts

**Comment by felipepessoto** [comment]
@allisonport-db gentle ping

**Pull request closed without merging**
