### PR TITLE
Remove the check that disables writes to Delta tables with deletion vectors

### PR DESCRIPTION
**Pull request by vkorukanti**
Given that now we have support for writing into DV tables and table utility operations as part of the delta-io/delta#1485 and delta-io/delta#1591, we should remove the check.

### CODE REVIEW

**Comment by xupefei** [comment]
There's one left: `shouldWritePersistentDeletionVectors` in `DeleteCommand.scala`.

**Review by larsk-db — APPROVED** [review]
LGTM

**Comment by vkorukanti** [comment]
> shouldWritePersistentDeletionVectors

I think we need this. This decides whether to generate DVs or not. Let me know if this is not the case.

**Comment by felipepessoto** [comment]
> > shouldWritePersistentDeletionVectors
> 
> I think we need this. This decides whether to generate DVs or not. Let me know if this is not the case.

I think he means this: `Utils.isTesting` in the shouldWritePersistentDeletionVectors method

https://github.com/delta-io/delta/blob/5c3f4d37951ab4edf1cc3364ec6e8259844b331c/core/src/main/scala/org/apache/spark/sql/delta/commands/DeleteCommand.scala#L444

**Comment by vkorukanti** [comment]
> > > shouldWritePersistentDeletionVectors
> > 
> > 
> > I think we need this. This decides whether to generate DVs or not. Let me know if this is not the case.
> 
> I think he means this: `Utils.isTesting` in the shouldWritePersistentDeletionVectors method
> 
> https://github.com/delta-io/delta/blob/5c3f4d37951ab4edf1cc3364ec6e8259844b331c/core/src/main/scala/org/apache/spark/sql/delta/commands/DeleteCommand.scala#L444

Ah, I missed that. Thank you!

**Comment by felipepessoto** [comment]
These lines were added when we blocked DV, but I think we don't use:

https://github.com/delta-io/delta/blob/5c3f4d37951ab4edf1cc3364ec6e8259844b331c/core/src/test/scala/org/apache/spark/sql/delta/deletionvectors/DeletionVectorsSuite.scala#L607-L609

**Review by felipepessoto — COMMENTED** [review]
These lines were added when we blocked DV, but I think we don't use:

https://github.com/delta-io/delta/blob/5c3f4d37951ab4edf1cc3364ec6e8259844b331c/core/src/test/scala/org/apache/spark/sql/delta/deletionvectors/DeletionVectorsSuite.scala#L607-L609

And these files
+ core/src/test/resources/delta/table-with-dv-feature-enabled/_delta_log/00000000000000000000.json
+ core/src/test/resources/delta/table-with-dv-feature-enabled/part-00000-fe8a3447-d858-4d61-ba30-9549910bc73d-c000.snappy.parquet

**Review by felipepessoto — APPROVED** [review]

**Pull request closed without merging**
