### PR TITLE
[DELTA][METRICS] custom metrics system support.

### PR DESCRIPTION
**Pull request by cfmcgrady**
add new interface `com.databricks.spark.util.EventLogging`，so that people can custom event data output.
With these event data, we can do more jobs. e.g we can do automatic optimize.

### CODE REVIEW

**Comment by databricks-cla-assistant** [comment]
[CLA assistant check](https://cla.dev.databricks.com/delta-io/delta?pullRequest=103) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.databricks.com/delta-io/delta?pullRequest=103) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dev.databricks.com/check/delta-io/delta?pullRequest=103) it.</sub>

**Comment by tdas** [comment]
Hey @cfmcgrady, thank you for your contribution. This is a good idea in general. We are little occupied right now with the imminent 0.3.0 release. Please bear with us, we will get back to you soon after that.

**Comment by mukulmurthy** [comment]
@tdas, can you review this one?

**Comment by rahulsmahadev** [comment]
@cfmcgrady 54643efc07dfaa9028d228dcad6502d59e4bdb3a added metrics for `Merge` and `Write` Commands via a new field in the CommitInfo called `OperationMetrics`. I am also working on a followup which would include metrics for Update, Delete and Streaming Update.

**Comment by zsxwing** [comment]
Closing this. We have added operation metrics. See https://docs.delta.io/latest/delta-utility.html#operation-metrics-keys

**Pull request closed without merging**
