### PR TITLE
[Blocked] 1385 collect stats on convert api

### PR DESCRIPTION
**Pull request by amirmor1**
## Description

Resolves https://github.com/delta-io/delta/issues/1385

Created for a second PR as a request https://github.com/delta-io/delta/pull/1401#pullrequestreview-1129045397

First PR sets the collectStatistics on convert to true by default with additional changes to the SQL statement.
This PR completes the DeltaTable API changes to disable collectStats by request.

## How was this patch tested?

Unit tests. Added a few tests on this and on the first PR to covert this.

## Does this PR introduce _any_ user-facing changes?

Additional API to DeltaTable to disable collectStats.

### CODE REVIEW

**Comment by scottsand-db** [comment]
Hi @amirmor1 - now that https://github.com/delta-io/delta/pull/1401 has been merged, want to continue on this?

**Comment by amirmor1** [comment]
Hi @scottsand-db , I've merged master, but since it was a while ago and we split to two PR's, it is possible that I forgot something on the way.

**Comment by amirmor1** [comment]
Hi @scottsand-db , no worries about the late review, its completely understanable.

Personally I don't need this option to be set to false, but the original request came from @MrPowers , so I suggest maybe he should advise on this.

**Comment by scottsand-db** [comment]
@amirmor1, I see. Thanks for clarifying! Yup we can go ahead and close this then.

**Pull request closed without merging**
