### PR TITLE
Add option to overwrite on first batch of stream

### LINKED ISSUE #1231: Delta Stream overwrite possibility
I'm using spark stream to append data to delta table,but i need only the latest data(data of latest file recieved in each partition). As stream doesn't support overwrite, is there any work around? Can we keep only the latest files in each partition and vacuum rest.
Is there any way to use overwrite in spark stream?
Urgent help needed

### PR DESCRIPTION
**Pull request by Kimahriman**
## Description

Resolves https://github.com/delta-io/delta/issues/1346

Adds the option to overwrite a table on the first batch of a new stream. See the issue for the use case. I wasn't sure what to name the config so definitely open to other options if this is an acceptable addition.

## How was this patch tested?

New UTs

## Does this PR introduce _any_ user-facing changes?

Adds a new option for streaming writes.

### CODE REVIEW

**Comment by scottsand-db** [comment]
Awesome. I'll take a look. thanks!

**Comment by scottsand-db** [comment]
Is this change really needed if we can accomplish it using the proposed `foreachBatch` solution here? https://github.com/delta-io/delta/issues/1346#issuecomment-1235454065

**Comment by Kimahriman** [comment]
It's not _needed_ but just a nice to have I guess. We're probably going to use one of these approaches for most/all of our ETL jobs, so it would just be nice have the streams be a little cleaner.

**Comment by scottsand-db** [comment]
I don't think we should add code like this into Delta Lake for very custom purposes such as yours. If you can find other community members that also need this API, then this is something that we can consider.

Else, I imagine a world where all sorts of users are submitting PRs with custom APIs/configs all doing niche custom things.

What do you think?

**Comment by Kimahriman** [comment]
There's at least 2 people who need it! I know I'm biased but it seems like a common problem people would have...

**Comment by scottsand-db** [comment]
@Kimahriman - perhaps you can make a PR to add an example instead? https://github.com/delta-io/delta/tree/master/examples

Since there is some pretty simple code that solves this problem, instead of embedding it into delta, im inclined to close this issue. I think having an example instead would be very useful and discoverable for future users.

If this use case pops up again, we can reconsider this.

**Comment by zsxwing** [comment]
One more point: we don't want to introduce non standard write mode in Delta sink. It's better to just follow Structured Streaming write mode behaviors, and anyone who wants non standard behaviors can leverage foreachBatch instead.

**Pull request closed without merging**
