### PR TITLE
[Docs] Adding all the markdown source files for docs.delta.io

### PR DESCRIPTION
**Pull request by tdas**
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [x] Other (fill in here) - Docs

## Description
This PR adds all the source files for generating the docs.delta.io
 

## How was this patch tested?
Currently manually tested by `python docs/generate_docs.py --livehtml`

### CODE REVIEW

**Comment by scottsand-db** [comment]
Is there any prerequisite to getting this script to work?

```
➜  ~/delta git:(docs) python docs/generate_docs.py --livehtml
Building content
/bin/sh: sphinx-autobuild: command not found
Traceback (most recent call last):
  File "docs/generate_docs.py", line 112, in <module>
    main()
  File "docs/generate_docs.py", line 46, in main
    run_cmd(build_docs_args, env=env, shell=True, stream_output=True)
  File "docs/generate_docs.py", line 93, in run_cmd
    raise Exception("Non-zero exitcode: %s" % exit_code)
Exception: Non-zero exitcode: 127
```

**Comment by vkorukanti** [comment]
Instructions in `docs/README.md` work. Just need to setup the conda environment by following the instructions in `docs/README.md` and then the command `python docs/generate_docs.py --livehtml` generates the docs locally.

**Review by vkorukanti — APPROVED** [review]
lgtm. tested the doc gen locally.

**Review by scottsand-db — CHANGES_REQUESTED** [review]
As discussed offline, please add a README that describes setting up the conda environment

**Review by allisonport-db — APPROVED** [review]
LGTM works locally for me

**Pull request merged**
