### PR TITLE
Minor code enhancements

### PR DESCRIPTION
**Pull request by takezoe**
Includes following fixes:
- Use StandardCharsets.UTF_8 instead of “utf-8”
- Remove unnecessary return statement
- Fix typo in error message
- Fix warnings

### CODE REVIEW

**Comment by mukulmurthy** [comment]
Hi @takezoe, thanks for your contributions! Would you mind merging this PR with your other two? 
https://github.com/delta-io/delta/pull/61
https://github.com/delta-io/delta/pull/62

For feature PRs or behavioral changes, it makes sense to separate everything, but for minor changes like these it's easier to merge them if they're combined. 

Thanks!

**Comment by takezoe** [comment]
Sure. I will push them into this PR.

**Comment by zsxwing** [comment]
@takezoe Thanks for your PR. Looks good to me. There are some minor conflicts. Could you resolve them?

**Comment by takezoe** [comment]
Rebased.

**Comment by zsxwing** [comment]
Thanks for your contribution. I have merged your PR.

**Pull request closed without merging**
